name: CI
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Coverage
        run: npm run codecov
